# SPDX-FileCopyrightText: 2026 Duncan McDougall <duncan.mcdougall@rfi.ac.uk>
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "datargs"
version = "0.2.0"
description = "Library for turning dataclasses into argparser args and gui."
readme = "README.md"
authors = [
    { name = "McDougall", email = "Duncan.McDougall@rfi.ac.uk" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "pyside6>=6.11.0",
]

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "icecream>=2.1.10",
    "pytest>=9.0.2",
    "line-profiler>=5.0.1",
    "pytest-autoprofile>=0.19.0",
    "pytest-cov>=7.0.0",
    "snakeviz>=2.2.2",
]

[tool.pytest]
testpaths = ["./tests", "./src/"]
addopts = ["--doctest-modules", "--cov=./src/", "--cov-report=html", "--cov-branch"]
